services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./container_logs/nginx:/var/log/nginx
      - ./public_html:/home/node/public_html
      - ./secrets/nginx:/etc/ssl
    environment:
      - NGINX_PORT=80
      - NGINX_PROXY=http://application:3001
      - NGINX_CERT_DIR=/etc/ssl
      - NGINX_CERT=selfsigned.crt
      - NGINX_KEY=selfsigned.pfx
      - NGINX_SSL_PORT=443
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - application
    restart: always

  application:
    image: wt1-express-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/home/node/
    command: "npm start"
